name: Monthly WhatsApp Rent Reminder

on:
  workflow_dispatch:   # Allows manual test runs
  schedule:
    # Runs on the 2nd of every month at 22:50 IST (17:20 UTC)
    - cron: "20 17 2 * *"

jobs:
  send-rent-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run WhatsApp rent reminder
        env:
          WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MENTION_WAID: ${{ secrets.MENTION_WAID }}
        run: python send_message.py
