name: Monthly WhatsApp Rent Reminder

on:
  schedule:
    # Runs automatically on the 4th of every month at 10:15 AM IST (04:45 UTC)
    - cron: "45 4 4 * *"
    # Backup run at 10:20 AM IST (04:50 UTC)
    - cron: "50 4 4 * *"
  workflow_dispatch:  # Allows manual testing

jobs:
  send-rent-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run WhatsApp rent reminder
        env:
          WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MENTION_WAID: ${{ secrets.MENTION_WAID }}
          MENTION_NAME: ${{ secrets.MENTION_NAME }}
        run: python send_message.py
