name: Monthly WhatsApp Rent Reminder

on:
  schedule:
    # Runs automatically on the 3rd of every month at 19:00 IST (13:30 UTC)
    - cron: "30 13 3 * *"
  workflow_dispatch:  # Allows manual testing

jobs:
  send-rent-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run WhatsApp rent reminder
        env:
          WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MENTION_WAID: ${{ secrets.MENTION_WAID }}
          MENTION_NAME: ${{ secrets.MENTION_NAME }}
        run: python send_message.py
