name: Scheduled WhatsApp Rent Reminder

on:
  schedule:
    - cron: "0 5 4 * *"  # Runs at 05:00 UTC (10:30 AM IST on the 4th)
  workflow_dispatch:  # Allows you to run manually too

jobs:
  send-rent-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run WhatsApp rent reminder (scheduled)
        env:
          WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MENTION_WAID: ${{ secrets.MENTION_WAID }}
        run: |
          echo "Sending WhatsApp message..."
          python send_message.py
