name: Test WhatsApp Rent Reminder

on:
  schedule:
    - cron: "0 6 4 * *"  # Runs automatically at 11:30 AM IST on the 4th day of every month
  workflow_dispatch:       # Also allows you to run manually if needed

jobs:
  send-rent-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run WhatsApp rent reminder
        env:
          WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MENTION_WAID: ${{ secrets.MENTION_WAID }}
        run: |
          echo "📩 Sending WhatsApp message..."
          python send_message.py
