name: WhatsApp Rent Reminder - Auto 4th 11:00AM IST

on:
  schedule:
    # Runs automatically at 05:30 UTC = 11:00 AM IST, on the 4th of every month
    - cron: "30 5 4 * *"
  workflow_dispatch:  # Optional: lets you test manually anytime

jobs:
  send-rent-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Send WhatsApp rent reminder
        env:
          WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MENTION_WAID: ${{ secrets.MENTION_WAID }}
          MENTION_NAME: ${{ secrets.MENTION_NAME }}
        run: |
          echo "🕚 Scheduled message triggered for 11:00 AM IST (04:30 UTC)"
          python send_message.py
