name: WhatsApp Rent Reminder - 4th Nov 11:00AM IST

on:
  schedule:
    # Runs once at 05:30 UTC (11:00 AM IST) on November 4
    - cron: "30 5 4 11 *"
  workflow_dispatch:  # Allows you to manually trigger for testing

jobs:
  send-rent-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Send WhatsApp rent reminder
        env:
          WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MENTION_WAID: ${{ secrets.MENTION_WAID }}
        run: |
          echo "🕚 Scheduled message triggered at 11:00 AM IST on Nov 4"
          python send_message.py
